[1.13.5]
Title = "Version 1.13.5"
Description = [ "[Bug]: Fix the GitHub release workflow",]
GitHubIssues = [ 0,]

[0.0.1]
Title = "Version 0.0.1"
Description = [ "Apply PackageIt.",]
GitHubIssues = [ 0,]

[0.0.0]
Title = "Version 0.0.0"
Description = [ "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
GitHubIssues = []
